# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Some notes
tagline:             ''
description:         ''
url:                 ''
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Dragos Tatulea
  url:               https://twitter.com/DragosTatulea
  email:             nope@yes.no

# Custom vars
version:             1.0.0
